colors:
  §0: black
  §1: dark_blue
  §2: dark_green
  §3: dark_aqua
  §4: dark_red
  §5: dark_purple
  §6: gold
  §7: gray
  §8: dark_gray
  §9: blue
  §a: green
  §b: aqua
  §c: red
  §d: light_purple
  §e: yellow
  §f: white
shopmenu:
  itemname: §6
  buy: §b
  buyprice: §1
  sell: §b
  sellprice: §1
  stock: §b
  stockamount: §1
managemenu:
  itemname: §6
  buy: §b
  buyprice: §1
  buymode: §9
  sell: §b
  sellprice: §1
  sellmode: §9
  stock: §b
  stockamount: §1
  status: §b
  statusvalue: §1
